---
- name: Secure ELK host group SongketMail

# https://ryaneschinger.com/blog/securing-a-server-with-ansible/
# lynis https://github.com/tommarshall/ansible-role-lynis

  vars:
    ubuntu_common_required_packages:
      - ufw
      - fail2ban
      - unattended-upgrades
      - apt-transport-https

    ubuntu_common_optional_packages:
      - mosh
      - vim
      - rsnapshot
      - chkrootkit
      - byobu

    ubuntu_common_ssh_port: 22
    ubuntu_common_mosh_from_port: 60000
    ubuntu_common_mosh_to_port: 60010

    lynis_cron_hour: 3
    lynis_cron_minute: 30
    lynis_log_directory: /var/log/lynis

  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
       upgrade: dist
       update_cache: yes

    - name: Install required packages
      apt: state=installed pkg={{ item }}
      with_items: "{{ ubuntu_common_required_packages }}"

    - name: Install optional packages
      apt: state=installed pkg={{ item }}
      with_items: "{{ ubuntu_common_optional_packages }}"

    - name: Setup ufw
      ufw: state=enabled policy=allow

    - name: Allow ssh traffic
      ufw: rule=allow port={{ ubuntu_common_ssh_port }} proto=tcp

    - name: Allow mosh traffic
      ufw: rule=allow proto=udp port={{ ubuntu_common_mosh_from_port }}:{{ ubuntu_common_mosh_to_port }}
      when: "'mosh' in ubuntu_common_optional_packages"

    - name: Disallow root SSH access
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PermitRootLogin"
                  line="PermitRootLogin no"
                  state=present
      notify: Restart ssh

    - name: Lynis | Install Lynis from apt
      apt:
        name=lynis
        state=present
        force=no
        install_recommends=no
        update_cache=yes
      register: lynis_isinstalled
      tags: lynis

    - name: Ensure Lynis log directory exists.
      file:
        path: "{{ lynis_log_directory }}"
        state: directory
        mode: 0750
      become: yes

    - name: Configure Lynis cron task.
      cron:
        name: Run Lynis
        cron_file: lynis
        minute: "{{ lynis_cron_minute }}"
        hour: "{{ lynis_cron_hour }}"
        user: root
        job: lynis audit system --auditor "automated" --cronjob > {{ lynis_log_directory }}/report-$(hostname).$(date +%Y%m%d).txt && mv /var/log/lynis.log {{ lynis_log_directory }}/report-log-$(hostname).$(date +%Y%m%d).log && mv /var/log/lynis-report.dat {{ lynis_log_directory }}/report-data-$(hostname).$(date +%Y%m%d).txt >/dev/null 2>&1
      become: yes
